### PR TITLE
create a software as a service app using ruby on rails

### PR DESCRIPTION
**Pull request by fadhili-ed**
Create a form from which data will be taken and saved in a db. after which the data in the db will be shown

### CODE REVIEW

**Comment by sigu** [comment]
Which part of the of the [guides](https://guides.rubyonrails.org/getting_started.html) are you?

**Comment by sigu** [comment]
Hint: each section can be a commit message e.g 
when you are done with [this section](https://guides.rubyonrails.org/getting_started.html#setting-the-application-home-page) you commit with message `setting the application home-page`

after finishing [this section](https://guides.rubyonrails.org/getting_started.html#laying-down-the-groundwork) you commit with message `laying down the groundwork`

**Comment by fadhili-ed** [comment]
nimefika kwa kulist all of the articles
sawa, i was thinking of doing that but adding some little explanation to the commits

**Comment by sigu** [comment]
Please provide the link @fadhili-ed

**Comment by sigu** [comment]
> nimefika kwa kulist all of the articles
> sawa, i was thinking of doing that but adding some little explanation to the commits

It's nice to add the comments as you are doing, I was just giving a hint on how often you can commit. Your current messages are great 👍

**Comment by fadhili-ed** [comment]
thanks, niprovide link ya nini?

**Comment by fadhili-ed** [comment]
im at 5.8 listing all articles ndo hii link: https://guides.rubyonrails.org/getting_started.html

**Pull request merged**
